### ISSUE TITLE
write to always concrete memory name:ConcreteCpuRegisters

### ISSUE THREAD

**Issue by bannsec** [S2E/libs2eplugins#14] opened 2017-08-07 22:07 UTC
So I've run into the following error messages a lot with S2E and Linux ELF x64 binaries:

```
KLEE: WARNING: silently concretizing (instruction: tcg-llvm-tb-7f36da480ab4-2c-444-0-40c2b7:   store i64 %9, i64* %11) (reason: write to always concrete memory name:ConcreteCpuRegisters offset=0x218 value=(Or w64 (Shl w64 (ReadLSB w64 0x4 v0_pass_0)
                 (w64 0x20))
        (ReadLSB w64 0x0 v0_pass_0))) expression (Or w64 (Shl w64 (ReadLSB w64 0x4 v0_pass_0)
                 (w64 0x20))
        (ReadLSB w64 0x0 v0_pass_0)) to value 0x0
KLEE: WARNING: silently concretizing (instruction: tcg-llvm-tb-7f36da480ab4-2c-444-0-40c2b7:   store i64 %13, i64* %15) (reason: write to always concrete memory name:ConcreteCpuRegisters offset=0x220 value=(Or w64 (Shl w64 (ZExt w64 (Concat w40 (w8 0x1)
                                       (ReadLSB w32 0xc v0_pass_0)))
                 (w64 0x20))
        (ReadLSB w64 0x8 v0_pass_0))) expression (Or w64 (Shl w64 (ZExt w64 (Concat w40 (w8 0x1)
                                       (ReadLSB w32 0xc v0_pass_0)))
                 (w64 0x20))
        (ReadLSB w64 0x8 v0_pass_0)) to value 0x0
```

After researching and banging my head on this, I've come up with a partial solution. The above errors, for me at least, tend to be when symbolic data has run off into libc. The GNU Libc likes to use SSE registers, which are not currently supported by KLEE. One (imperfect) solution I have found is to basically swap out those libc functions with another library that doesn't utilize SSE as much. In this case, I have been using `musl`. The following is an example:

bootstrap.sh
```bash
LD_PRELOAD=./libc-musl-jessie.so ./${TARGET}  > /dev/null 2> /dev/null
```

Obviously you need to copy the musl library over and such, but that's the idea.

One problem I have run into is when attempting to use LD_PRELOAD to load `musl` __as well as__ `s2e.so`. In my experience, this tends to cause a segfault. Likely, this is due to how s2e is actually interacting with the environment. Unfortunately, I don't know enough about how `s2e.so` actually behaves to attempt to make it work with something like `musl`. 

Case 1:
```
S2E_SYM_ARGS="1" LD_PRELOAD=./libc-musl-jessie.so:./s2e.so
```

In this case, `s2e.so` doesn't appear to load or run correctly. For instance, it does not change the argument to symbolic.

Case 2:
```
S2E_SYM_ARGS="1" LD_PRELOAD=./s2e.so:./libc-musl-jessie.so
```

Case 2 causes a segfault.

Given that `musl` and possibly other drop-in library replacement could be beneficial for getting past a limitation in KLEE, it would be good to figure out how to get `s2e.so` to place nicely with other things being PRELOADed with it.

**Comment by vitalych** [comment] 2017-08-08 18:23
The problem is not klee, but S2E. SSE registers are stored in the concrete region of the cpu state. It should be possible to move them to the symbolic region (right before eip). You would also have to wrap every access to these registers from the helper code, to redirect the access to the proper state, just like for general purpose registers.

**Comment by Owlz** [comment] 2017-08-09 12:51
Could you provide more information about how that would work? I don't have enough experience w/ S2E internals to understand what you're talking about.

**Comment by vitalych** [comment] 2017-08-09 13:00
Section 4 in http://dslab.epfl.ch/pubs/s2e-tocs.pdf provides an overview of how it works. Let me know if you have more questions.

**Comment by adrianherrera** [comment] 2017-08-09 13:33
Hi @Owlz,

"move them [the SSE registers] to the symbolic region (right before eip)" refers to the `CPUX86State` struct, defined at https://github.com/S2E/libcpu/blob/master/include/cpu/i386/cpu.h#L77 (you can see the comment regarding symbex above the `eip` field).

If I had to guess (I haven't done much with this code before, so I'm sure I'll be corrected if I'm wrong), the helper functions are those set by https://github.com/S2E/libs2e/blob/master/src/s2e-libcpu-interface.c#L30

For example, if you trace ` sqi->regs.read_concrete` you will see that it goes through https://github.com/S2E/libs2ecore/blob/master/src/S2EExecutionState.cpp#L1215. If you follow this code through you should see how the symbolic region works.

Hopefully this helps at where to look in the code!

**Comment by Owlz** [comment] 2017-08-14 01:51
Hmmm. So I moved up the XMM register lines in `libcpu/include/cpu/i386/cpu.h` up above eip. Looking through the helper calls, it's not clear to me what has to be changed for this. I traced it down through here:

https://github.com/S2E/libs2ecore/blob/565e63aa4bacc5ed49595cfeaa26dad3a35e70ad/src/S2EExecutionStateRegisters.cpp#L155

I compiled the change anyway to see what happens and, upon running the program, it causes a segfault of QEMU.

Any further pointers on what needs to be accounted for would be welcome :-)

**Comment by adrianherrera** [comment] 2017-08-15 06:40
Hey @Owlz,

There's not much I can do with "it causes a segfault". Can you please use the debug build (`s2e build -g`) and run in gdb (`./launch-s2e.sh debug`) and paste the stack trace here. That way we can at least see what caused the segfault.

~Adrian

**Comment by Owlz** [comment] 2017-08-16 02:51
So i tried to rebuild with that command `s2e build -g`, and when it got to the following part, it chewed up all 8 Gigs and crashed my comp:

```
[100%] Linking CXX executable ../../../../bin/clang-check
```

I gave it a run anyway and it seems to be working? Here's the output

```
(gdb) r
Starting program: /home/s2e/s2e/build/s2e/qemu-debug/i386-softmmu/qemu-system-i386 -drive file=/home/s2e/s2e/images/debian-8.7.1-i386/image.raw.s2e,format=s2e,cache=writeback -k en-us -nographic -monitor null -m 256M -enable-kvm -serial file:serial.txt -net none -net nic,model=e1000 -loadvm ready
ERROR: ld.so: object '/home/s2e/s2e/build/s2e/libs2e-debug/i386-s2e-softmmu/libs2e.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/home/s2e/s2e/build/s2e/libs2e-debug/i386-s2e-softmmu/libs2e.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

(process:1786): GLib-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmem.c:483: custom memory allocation vtable not supported
[New Thread 0x7ffff1cbc700 (LWP 1790)]
Warning: vlan 0 is not connected to host network
s2e-block: dirty sectors on close:0
s2e-block: dirty after restore: 184 (ro=0)
s2e-block: wasted sectors: 200
KVM: entry failed, hardware error 0x80000021

If you're running a guest on an Intel machine without unrestricted mode
support, the failure can be most likely due to the guest entering an invalid
state for Intel VT. For example, the guest maybe running in big real mode
which is not supported on less recent Intel processors.

EAX=00000000 EBX=00000002 ECX=ffffffff EDX=b7724878
ESI=bfbf9ca4 EDI=bfbfaf14 EBP=00000000 ESP=bfbe9bf0
EIP=080487d0 EFL=00000246 [---Z-P-] CPL=3 II=0 A20=1 SMM=0 HLT=0
ES =007b 00000000 ffffffff 00c0f300 DPL=3 DS   [-WA]
CS =0073 00000000 ffffffff 00c0fb00 DPL=3 CS32 [-RA]
SS =007b 00000000 ffffffff 00c0f300 DPL=3 DS   [-WA]
DS =007b 00000000 ffffffff 00c0f300 DPL=3 DS   [-WA]
FS =0000 00000000 00000000 00000000
GS =0033 b7579940 ffffffff 00d0f300 DPL=3 DS   [-WA]
LDT=0000 00000000 00000000 00008200 DPL=0 LDT
TR =0080 cfdef4c0 0000206b 00008900 DPL=0 TSS32-avl
GDT=     cfde6000 000000ff
IDT=     fffba000 000007ff
CR0=80050033 CR2=b7750000 CR3=0e48b000 CR4=00000690
DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
DR6=ffff0ff0 DR7=00000400
EFER=0000000000000000
Code=30 8e 04 08 e8 ab fd ff ff 83 c4 10 90 90 90 90 90 90 90 90 <31> c0 0f 3f 00 00 00 00 00 00 00 00 85 c0 74 f0 83 ec 0c 68 50 8e 04 08 e8 83 fd ff ff 83
```

However, my guess is those errors are because the debug build failed to complete due to not having enough memory to compile it.

**Comment by adrianherrera** [comment] 2017-08-17 08:23
Oh, that's kinda depressing :( I'm also back to using a regular desktop PC to do my S2E work (previously I was working on some 50-core machine with loads of RAM), so I feel your pain.

I actually spent a little bit of time looking at this yesterday. I think this is what we have to do:

* move the `xmm_regs` array in `CPUX86State` above `eip`
* intercept access to `xmm_regs` in libcpu

To see how register accesses are intercepted for the general purpose (GP) registers (EAX, EBP, etc.) you can look in src/target-i386/cpu.h in libcpu. In there you should see 2 macros, `__RR_env_raw` and `_WR_env_raw` that call `g_sqi.regs.{read,write}_concrete`, which ultimately ends up calling `S2EExecutionState::readSymbolicRegion` through `s2e_read_register_concrete` in libs2ecore/src/S2EExecutionState.cpp.

The `__{R,W}R_env_raw` macros end up getting aliased by `{R,W}R_cpu` (still in src/target-i386/cpu.h). Further down that header file you should see read/write macros for each of the GP registers, `EAX`, `EAX_W`, etc. These basically get used whenever a GP register is read from/written to in libcpu.

For example, in `switch_tss` in src/target-i386/op_helper.c you can see these macros being used to write to EAX, ECX, etc. If you compare this function to the original code in (S2E's) QEMU in `target-i386/op_helper.c` you can see that `EAX = new_regs[0]` is used instead of using `EAX_W(new_regs[0])`. In this case the `EAX` macro is defined as `(env->regs[R_EAX])`.

So what's happening here is that instead of writing to `env->regs[R_EAX]` directly, libcpu instead goes via `EAX_W` and reads/writes register values from/into the symbolic region in `S2EExecutionState`.

So we'll need to do the same thing for `env->xmm_regs` - i.e. whenever they are read/written from/to in libcpu, we will have to use a similar process. I'm not sure if we can directly reuse the existing `__{W,R}R_env_raw` macros, because they assume that the register is a `target_ulong`, whereas each XMM register is a union which includes a `float`, and tbh I'm not 100% sure what to do about the `float`.

Sorry, I rambled quite a bit. I hope something in there makes sense!

**Comment by vitalych** [comment] 2017-08-17 16:48
Also, for the crash above, you can't resume snapshots if cpu state changed. You must take a new snapshot.

**Comment by Owlz** [comment] 2017-08-19 06:34
Ahhh. Thanks for the extra info all! Gotten super busy lately, but will definitely return back to this soon.

**Comment by bannsec** [comment] 2017-11-01 03:41
Hey guys. I've looked at this periodically since you posted how it should work and i think i understand what you're talking about. However, I haven't been able to get it to work and also am not sure how to deal with it not being a direct integer type register. Any other thoughts on this?

**Comment by adrianherrera** [comment] 2017-11-09 06:13
I'm not sure either. Specifically, I'm not sure how you deal with the `float` component of the union. Maybe @vitalych knows an obvious solution; he normally does :)

**Comment by vitalych** [comment] 2018-05-27 11:32
closing this issue for now

**Closed by vitalych** 2018-05-27 11:32 UTC
